# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1df8da4007bf60ef54e7b0e7686208dc23816a45dcfc512acdc16ae795ef26829cb80aeaee091a4f14562752483503240ab0db954d9918b690906e438d25fb

test:
  secret_key_base: 00b9262e727d4160614b8889c8caa4db2885f9db332137dc7e3e240fc50d7e7fcd6d4805d30e441901a5e61bf5d5253dbd7d607691d7493e5385f653dac6daa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


development:
  stripe_publishable_key: pk_test_GG8RyPUQj7hZmPKAFJwAgIDi
  stripe_secret_key: sk_test_gAIpIbTKoOe3VuupER3KZkRG

production:
  stripe_publishable_key: pk_test_GG8RyPUQj7hZmPKAFJwAgIDi
  stripe_secret_key: sk_test_gAIpIbTKoOe3VuupER3KZkRG
